apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tsidp
  namespace: general-services
  labels:
    app.kubernetes.io/name: tsidp
  annotations:
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@weekly"    
spec:
  selector:
    matchLabels:
      app: tsidp
  serviceName: "tsidp"
  replicas: 1
  minReadySeconds: 1
  template:
    metadata:
      labels:
        app: tsidp
      annotations:	
        linkerd.io/inject: enabled        
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tsidp
        image: ghcr.io/tailscale/tsidp:latest
        ports:
        - name: tsidp
          containerPort: 3001
        env:
          - name: TAILSCALE_USE_WIP_CODE
            value: 1
          - name: TS_STATE_DIR
            value: /data
          - name: TS_HOSTNAME
            value: idp
          - name: TSIDP_ENABLE_STS
            value: 1
          - name: TS_AUTHKEY
            value: 
        resources:
          limits:
            cpu: 500m
            memory: "536870912"
          requests:
            cpu: 250m
            memory: "268435456"
        volumeMounts:
          - name: tsidp-pvc
            mountPath: /data

  volumeClaimTemplates:
  - metadata:
      name: tsidp-pvc
      namespace: general-services
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "do-block-storage"
      resources:
        requests:
          storage: 2Gi
