apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-pvc
  namespace: media-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 2Gi
