apiVersion: v1
kind: volumeClaimTemplate
- metadata:
    name: jackett-pvc
    namespace: media-services
  spec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 2Gi
    storageClassName: do-block-storage
