apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jackett
  namespace: media-services
  labels:
    app.kubernetes.io/name: jackett
  annotations:
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@weekly"    
spec:
  selector:
    matchLabels:
      app: jackett
  serviceName: "jackett"
  replicas: 1
  minReadySeconds: 1
  template:
    metadata:
      labels:
        app: jackett
      annotations:	
        linkerd.io/inject: enabled        
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: jackett
        image: lscr.io/linuxserver/jackett:latest
        ports:
        - name: jackett
          containerPort: 9117
        env:
          - name: TZ
            value: America/Los_Angeles
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'              
        resources:
          limits:
            cpu: 500m
            memory: "536870912"
          requests:
            cpu: 250m
            memory: "268435456"
        volumeMounts:
          - mountPath: /config
            name: jackett-pvc
          - mountPath: /data/nzb
            name: jackett-nfs-nzb
          - mountPath: /data/torrent
            name: jackett-nfs-torrent
      volumes:
      - name: jackett-nfs-nzb
        nfs:
          server: 192.168.52.8
          path: /volume1/media/Holding/docker/nzb
          readOnly: false
      - name: jackett-nfs-torrent
        nfs:
          server: 192.168.52.8
          path: /volume1/media/Holding/docker/torrent
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: jackett-pvc
      namespace: media-services
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "do-block-storage"
      resources:
        requests:
          storage: 2Gi
