
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas01-torrent-pvc
spec:
  accessModes:
    - ReadWriteMany # Must match the access modes of the PV
  resources:
    requests:
      storage: 5Gi # Request the same or less storage than the PV capacity
  volumeName: nas01-torrent-pv # Explicitly bind to the PV by name  
