apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas01-torrent-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany # Or ReadWriteOnce, ReadOnlyMany depending on your needs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/media/Holding/docker/torrent
    server: 192.168.52.8
