apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oauth
  namespace: general-services
  labels:
    app: oauth
  annotations:
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@weekly"    
spec:
  selector:
    matchLabels:
      app: oauth
  serviceName: "oauth"
  replicas: 1
  minReadySeconds: 1	  
  template:
    metadata:
      labels:
        app: oauth
      annotations:	
        linkerd.io/inject: enabled        
    spec:
      terminationGracePeriodSeconds: 60    
      containers:
      - image: thomseddon/traefik-forward-auth:2
        name: oauth
        ports:
          - containerPort: 4181
            hostPort: 4181
            protocol: TCP      
        env:
          - name: CONFIG
            value: $CONFIG
          - name: DOMAIN
            value: $DOMAIN
          - name: OIDC_ISSUER
            value: $OIDC_ISSUER
          - name: AUTH_HOST
            value: $AUTH_HOST
          - name: PROVIDERS_GOOGLE_CLIENT_ID
            value: $PROVIDERS_GOOGLE_CLIENT_ID
          - name: SECRET
            value: $SECRET
          - name: PROVIDERS_GOOGLE_CLIENT_SECRET
            value: $PROVIDERS_GOOGLE_CLIENT_SECRET
          - name: COOKIE_DOMAIN
            value: $COOKIE_DOMAIN
          - name: URL_PATH
            value: $URL_PATH
          - name: WHITELIST
            value: $WHITELIST
          - name: DEFAULT_ACTION
            value: $DEFAULT_ACTION
          - name: DEFAULT_PROVIDER
            value: $DEFAULT_PROVIDER
          - name: INSECURE_COOKIE
            value: $INSECURE_COOKIE
          - name: LIFETIME
            value: $LIFETIME
          - name: LOG_FORMAT
            value: $LOG_FORMAT
          - name: LOG_LEVEL
            value: $LOG_LEVEL
          - name: TZ
            value: $TZ
        resources:
          limits:
            cpu: 500m
            memory: "536870912"
          requests:
            cpu: 250m
            memory: "134217728"
        volumeMounts:
          -  name: oauth-pvc
             mountPath: /config
  volumeClaimTemplates:
  - metadata:
      name: oauth-pvc
      namespace: general-services
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "do-block-storage"
      resources:
        requests:
          storage: 2Gi
