apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flaresolverr
  namespace: media-services
  labels:
    app.kubernetes.io/name: flaresolverr
  annotations:
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@weekly"    
spec:
  selector:
    matchLabels:
      app: flaresolverr
  serviceName: "flaresolver"
  replicas: 1
  minReadySeconds: 1	  
  template:
    metadata:
      labels:
        app: flaresolverr
      annotations:	
        linkerd.io/inject: enabled        
    spec:
      terminationGracePeriodSeconds: 10	
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        imagePullPolicy: Always          
        env:
          - name: LOG_LEVEL
            value: info
        ports:
          - name: flaresolverr
            containerPort: 8191
        resources:
          limits:
            cpu: 500m
            memory: "536870912"
          requests:
            cpu: 250m
            memory: "268435456"
